
format = """
[┌](bold bright-blue)\
[](bright-blue)\
$hostname\
[](fg:bright-blue bg:blue)\
$username\
[](bold fg:blue bg:bright-black)\
$sudo\
[](bright-black)\
$directory\
$git_branch\
[\\( ](yellow bold)\
$git_state\
$git_status\
$git_metrics\
[ \\)](yellow bold)[ ⟹ ](purple bold)[ { ](red bold)\
$fill\
$nodejs\
$python\
[ ](white)\
$cmd_duration$jobs$time\
[](white)\
$line_break\
[│](bold bright-blue)
[└─](bold bright-blue)[](bright-blue)[](cyan)$character\
"""

right_format = """
[ } ](red bold)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# [line_break]
# disabled = true

[username]
show_always = true
style_user = "bold fg:black bg:blue "
# style_root = "red bold"
# format = '[󰮭 $user]($style)'
format = '[ 󰚩 ]($style)'

[hostname]
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "bold bg:bright-blue fg:bright-white"
format = '[ ]($style)'

[sudo]
style = "bold fg:yellow bg:bright-black"
symbol = "󰉁"
# format = '[$symbol]($style)'
format = '[ $symbol ]($style)'
disabled = false

[fill]
symbol = " "
style = "bold white"

[directory]
style = "fg:blue bg:black"
read_only = " 󰌾"
repo_root_style = "fg:bright-blue bg:black bold"
truncation_length = 2
truncate_to_repo = false
truncation_symbol = " …/"

[directory.substitutions]
# "~" = "󰋜 "
"~" = "  "
"blender" = "󰂫 "
#"Documents" = "󰈙 "
"Documents" = "󱧶 "
"Downloads" = "󰉍 "
#".git" = " "
".git" = "󰊢 "
"Music" = "󱍙 "
"Pictures" = "󰉏 "
"wine" = "󰡶 "

[character]
# success_symbol = "[](purple)"
success_symbol = "[](green bold)"
error_symbol = "[󰚌](red)"
vicmd_symbol = "[](green)"

[git_branch]
symbol = "󰘬 "
format = "[$symbol$branch]($style) "
style = "purple bold"

[jobs]
symbol = "󰒓"
style = "fg:black bg:white"
number_threshold = 0
symbol_threshold = 1
format = "[ $symbol]($style)"

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = "check-git-remote"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash", "--noprofile", "--norc"]
format = "at $output  "

[git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# style = "cyan"
conflicted = "="

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[ $duration 󱎫]($style)"
style = "fg:black bg:white"

[memory_usage]
symbol = "󰍛 "


[nodejs]
symbol = ' 󰎙 '
format = "[$symbol($version )]($style)"

[python]
symbol = ' 󰌠 '
format = "[$symbol]($version)"

[rust]
symbol = " 󱘗 "

[time]
disabled = false
style = "fg:black bg:white"
format = "[ $time 󰥔 ]($style)"

[custom.zsh]
command = "echo 🚀"
when = """ test "$STARSHIP_SHELL" "==" "zsh" """
format = "$output"
